input_dir: ./
output_dir: ./
output_name: context.txt

allowed_extensions:
  - .go
  - .py
  - .yaml
  - .txt
  - .md

skip_dirs:
  - .git
  - __pycache__
  - .venv
  - node_modules
  - build
  - dist
